### ISSUE TITLE
Add Initialization File

### ISSUE THREAD

**Issue by emaicus** [youngcc3157/RedM_Text_Transformation#19]
Add an initialization file which is parsed upon program startup.

The file should contain
1. The address of the Indexing team
2. The address of the Crawling team
3. The address of the Link Analysis Team
4. The max size n-gram to compute
5. The number of threads to spin up (the number of concurrent calls we want to handle)

**Comment by snagglewhen** [comment]
We should not need the address of the Crawling team.  When they call our API we should be able to return the success or failure flag to the address that it was called from.

**Comment by snagglewhen** [comment]
This is actually a function, but it is there.
